@startchen DBKala_Full_ER
!theme toy
<style>
.derived {
    FontColor Blue
}
.new_base {
    BackgroundColor LightGreen
}
.tax_req {
    BackgroundColor LightYellow
}
.wallet_req {
    BackgroundColor LightCyan
}
.loyalty_req {
    BackgroundColor MistyRose
}
.feedback_req {
    BackgroundColor #F0E68C
}
.supplier_req {
    BackgroundColor #E6E6FA
}
.return_req {
    BackgroundColor #FFDAB9
}
.bnpl_req {
    BackgroundColor #E0FFF0
}
</style>

' --- ENTITIES ---

entity "Customer" as CUSTOMER {
    ID <<key>>
    Name
    Phone
    Email
    Age
    Gender
    IncomeLevel
    Nature
    Tier
    TaxAmount <<tax_req>>
    LoyaltyPoints <<derived>> <<loyalty_req>>
    CreditLimit <<derived>> <<bnpl_req>>
    Debt <<derived>> <<bnpl_req>>
}

entity "Order" as ORDER {
    ID <<key>>
    Date
    Priority
    TotalAmount <<derived>>
    PaymentMethod
    LoyaltyDiscount <<loyalty_req>>
}

entity "Product" as PRODUCT {
    ID <<key>>
    Name
    Category
    SubCategory
    BaseInfo
    TaxAmount <<tax_req>>
}

entity "Shipment" as SHIPMENT {
    ID <<key>>
    TrackingCode
    Date
    RecipientAddress
    City
    ZipCode
    Type
    TransportMethod
    Cost
    PackType
    PackSize
}

entity "Warehouse" as WAREHOUSE {
    ID <<key>>
    Name
    Address
}

entity "Branch" as BRANCH <<new_base>> {
    ID <<key>>
    Name
    Address
    Phone
    SalesVolume
}

entity "Manager" as MANAGER <<new_base>> {
    ID <<key>>
    Name
}

entity "Supplier" as SUPPLIER <<supplier_req>> {
    ID <<key>>
    Name
    Phone
    Address
}

entity "Wallet" as WALLET <<wallet_req>> {
    ID <<key>>
    Balance
}

entity "WalletTransaction" as W_TRANS  <<wallet_req>> {
    ID <<key>>
    Type
    Amount
    Date
}

entity "ReturnRequest" as RETURN <<return_req>> {
    ID <<key>>
    RequestDate
    Reason
    ReviewResult
    DecisionDate
}

entity "RepaymentHistory" as REPAYMENT <<weak>> <<bnpl_req>> {
    Amount
    Date <<key>>
    PaymentMethod
}

relationship "places" as PLACES {
}

relationship "contains" as CONTAINS {
    Quantity
    CalculatedItemPrice <<derived>>
    ItemStatus <<return_req>>
}

relationship "shipped_via" as SHIPPED_VIA {
}

relationship "reviews" as REVIEWS <<feedback_req>> {
    Score
    Comment <<feedback_req>>
    Image <<feedback_req>>
    IsPublic <<feedback_req>>
}

relationship "manages" as MANAGES <<new_base>> {
}

relationship "owns" as OWNS <<new_base>> {
}

relationship "stores" as STORES {
    Quantity
}

relationship "offers_and_supplies" as OFFERS <<supplier_req>> {
    SellingPrice
    SupplyPrice <<supplier_req>>
    LeadTime <<supplier_req>>
    Discount
    IsAvailable
}

relationship "processed_at" as PROCESSED_AT <<new_base>> {
}

relationship "has_wallet" as HAS_WALLET <<wallet_req>> {
}

relationship "logs" as LOGS <<wallet_req>> {
}

relationship "requests_return" as REQ_RET <<return_req>> {
}

relationship "has_repayment" as HAS_REP <<bnpl_req>> <<identifying>>{
}

CUSTOMER -1- PLACES
PLACES =N= ORDER

ORDER =M= CONTAINS
CONTAINS -N- PRODUCT

ORDER =1= SHIPPED_VIA
SHIPPED_VIA =1= SHIPMENT

CUSTOMER -M- REVIEWS
REVIEWS -N- PRODUCT

MANAGER -1- MANAGES
MANAGES =N= BRANCH

BRANCH -1- PROCESSED_AT
PROCESSED_AT =N= ORDER

BRANCH -1- OWNS
OWNS =N= WAREHOUSE

WAREHOUSE -M- STORES
STORES -N- PRODUCT

BRANCH -M- OFFERS
OFFERS -N- PRODUCT
OFFERS -P- SUPPLIER

CUSTOMER =1= HAS_WALLET
HAS_WALLET =1= WALLET

WALLET -1- LOGS
LOGS =N= W_TRANS

CONTAINS -1- REQ_RET
REQ_RET =1= RETURN

ORDER -1- HAS_REP
HAS_REP =N= REPAYMENT

@endchen