@startchen req_1_2_3_strong_edges
<style>
.derived {
FontColor Blue
}
.new {
BackgroundColor LightGreen
}
.newreq2 {
BackgroundColor LightYellow
}
.newreq3 {
BackgroundColor LightCyan
}
.tax_req {
    BackgroundColor Yellow
}
</style>

' Entities
entity "Customer" as CUSTOMER {
    ID <<key>>
    Name
    Phone
    Email
    Age
    Gender
    IncomeLevel
    Nature
    Tier
    TaxAmount <<tax_req>>
}

entity "Order" as ORDER {
    ID <<key>>
    Date
    Priority
    ProcessStatus
    TotalAmount <<derived>>
    PaymentMethod
}

entity "Product" as PRODUCT {
    ID <<key>>
    Name
    Category
    SubCategory
    BaseInfo
    TaxAmount <<tax_req>>
}

entity "Shipment" as SHIPMENT {
    ID <<key>>
    TrackingCode
    Date
    RecipientAddress
    City
    ZipCode
    Type
    TransportMethod
    Cost
    PackType
    PackSize
}

entity "Warehouse" as WAREHOUSE {
    ID <<key>>
    Name
    Address
}

entity "Branch" as BRANCH <<new>> {
    ID <<key>>
    Name
    Address
    Phone
    SalesVolume
}

entity "Manager" as MANAGER <<new>> {
    ID <<key>>
    Name
}

' Relationships

relationship "places" as PLACES {
}

relationship "contains" as CONTAINS {
    Quantity
    CalculatedItemPrice <<derived>>
}

relationship "shipped_via" as SHIPPED_VIA {
}

relationship "reviews" as REVIEWS {
    Score
}

relationship "manages" as MANAGES <<new>> {
}

relationship "owns" as OWNS <<new>> {
}

relationship "stores" as STORES {
    Quantity
}

relationship "offers" as OFFERS <<new>> {
    SellingPrice
    Discount
    IsAvailable
}

relationship "processed_at" as PROCESSED_AT <<new>> {
}

CUSTOMER -1- PLACES
PLACES =N= ORDER

ORDER =M= CONTAINS
CONTAINS -N- PRODUCT

ORDER =1= SHIPPED_VIA
SHIPPED_VIA =1= SHIPMENT

CUSTOMER -M- REVIEWS
REVIEWS -N- PRODUCT

MANAGER -1- MANAGES
MANAGES =N= BRANCH

BRANCH -1- PROCESSED_AT
PROCESSED_AT =N= ORDER

BRANCH =1= OWNS
OWNS =N= WAREHOUSE

WAREHOUSE -M- STORES
STORES -N- PRODUCT

BRANCH -M- OFFERS
OFFERS -N- PRODUCT

@endchen